# Generated by Django 5.1.5 on 2025-02-03 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
