# Generated by Django 5.1.5 on 2025-02-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='about_title',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='degree',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
