# Generated by Django 5.1.5 on 2025-02-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_remove_portfolio_about_title_remove_portfolio_degree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
